
title: haveyoumetrahul
email: rhlvenugopal@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  This is my online avatar.
A human  being should be able to change a diaper, plan an invasion, butcher a  hog, conn a ship, design a building, write a sonnet, balance accounts,  build a wall, set a bone, comfort the dying, take orders, give orders,  cooperate, act alone, solve equations, analyze a new problem, pitch  manure, program a computer, cook a tasty meal, fight efficiently, die  gallantly. Specialization is for insects.  
baseurl: "haveyoumetrahul" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: rhlvenugopal
github_username:  

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
